### ISSUE TITLE
Sysl release workflow is not working

### ISSUE THREAD

**Issue by ChloePlanet** [anz-bank/sysl#755]
### Description
The sysl release machinery is not working. When building the release, `go.sum` is getting modified so the workspace is identified as dirty, which [breaks the release](https://github.com/anz-bank/sysl/runs/538539415?check_suite_focus=true). This is why we have not had a release since v0.29.0.

### Steps to Reproduce
1. merge PR to master
* Debug&Crash Output
```
   ⨯ release failed after 0.29s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
 M go.sum
```

**Comment by cuminandpaprika** [comment]
First issue:
- go sum file is dirty fixed in https://github.com/anz-bank/sysl/pull/754

Next issue:
The makefile isn't getting copied over correctly when the docker image is built using goreleaser
Step 6/11 : COPY . .
 ---> 64f086f7a424
Step 7/11 : RUN make build
 ---> Running in 747c75dbccc6
make: *** No rule to make target 'build'.  Stop.
The command '/bin/sh -c make build' returned a non-zero code: 2
: exit status 2

**Comment by cuminandpaprika** [comment]
Steps
- [ ] Merge workflows into one
- [ ] Add check-tidy so that branches with dirty go.mod and go.sum can't be merged in
- [ ] Build and upload the docker image using a github action
